#!/bin/sh

set -e

. $CETIC_6LBR_CONF
. `dirname $0`/6lbr-functions

config_default

for i in `ls $ETC_6LBR/ifdown.d`; do
	file=$ETC_6LBR/ifdown.d/$i
	if [ -x $file ]; then
		$file $LIB_6LBR "$@"
	fi
done
