#!/bin/sh

. $CETIC_6LBR_CONF
. $LIB_6LBR/6lbr-functions

MODE_6LBR=$1
DEV=$2
OS=`uname`

case $MODE_6LBR in
	raw)
	;;
	
	tap)
	case $OS in
		Linux)
			if [ "$BRIDGE" = "1" ]; then
				if [ "$CREATE_BRIDGE" = "1" ]; then
					ip link set $DEV_BRIDGE down
					brctl delbr $DEV_BRIDGE
					ip link set $DEV_ETH up
				else
					brctl delif $DEV_BRIDGE $DEV
				fi
			fi
			ip link set $DEV down
			netstat -nr | awk '{ if ($2 == "'$DEV'") print "route delete -net "$1; }' | sh
			;;
		Darwin)
			if [ "$BRIDGE" = "1" ]; then
				if [ "$CREATE_BRIDGE" = "1" ]; then
					ifconfig $DEV_BRIDGE destroy
				else
					ifconfig $DEV_BRIDGE delm $DEV
				fi
			fi
			;;
		*)
			echo Unknown OS
	esac
	;;
	
	*)
	echo "Unknown mode $MODE"
	;;
esac
