#!/bin/bash

. $CETIC_6LBR_CONF
. `dirname $0`/6lbr-functions

config_default

MODE_6LBR=$1
DEV=$2
OS=`uname`

case $MODE_6LBR in
	raw)
	;;
	
	tap)
	case $OS in
		Linux)
			if [ "$BRIDGE" = "1" ]; then
				if [[ "$CREATE_BRIDGE" = "6LBR" || "$CREATE_BRIDGE" = "1" ]]; then
					ip link set $DEV_BRIDGE down
					ip addr flush dev $DEV_BRIDGE
					ip addr flush dev $DEV
					brctl delbr $DEV_BRIDGE
				else
					brctl delif $DEV_BRIDGE $DEV
				fi
			fi
			ip link set $DEV down
			netstat -nr | awk '{ if ($2 == "'$DEV'") print "route delete -net "$1; }' | sh
			;;
		Darwin)
			if [ "$BRIDGE" = "1" ]; then
				if [ "$CREATE_BRIDGE" = "1" ]; then
					ifconfig $DEV_BRIDGE destroy
				else
					ifconfig $DEV_BRIDGE delm $DEV
				fi
			fi
			;;
		*)
			echo Unknown OS
	esac
	;;
	
	*)
	echo "Unknown mode $MODE"
	;;
esac
