PROJECT=6lbr-demo-delay

CONTIKI=../../../../../..
PROJECTDIRS+=../../../../../6lbr-demo/

WITH_SHELL=1
WITH_DELAY_IP=1
WITH_UDPCLIENT=1
WITH_WEBSERVER=0
UDP_PERIOD=5
WITH_UDP_CLIENT_AUTOSTART=0

include ../../../../../6lbr-demo/Makefile
