CFLAGS += -DCETIC_NODE_INFO=1
node-info_src = node-info.c

ifeq ($(TARGET),native)
CFLAGS += -DCETIC_NODE_INFO_EXPORT=1
node-info_src += node-info-export.c
ifneq ($(WITH_WEBSERVER),0)
node-info_src += webserver-node-info-export.c
endif
endif

ifeq ($(TARGET),cooja)
CFLAGS += -DCETIC_NODE_INFO_EXPORT=1
node-info_src += node-info-export.c
ifneq ($(WITH_WEBSERVER),0)
node-info_src += webserver-node-info-export.c
endif
endif
