6LBR_PLUGIN=coap-mqtt-proxy.so

6LBR=../..
PLUGIN_SOURCEFILES+=coap-mqtt-proxy.c

PROJECTDIRS+=$(6LBR)/../6lbr-demo/apps/coap $(CONTIKI)/apps/er-coap $(CONTIKI)/apps/rest-engine

include $(6LBR)/Makefile
