#!/bin/sh

set -e

. $CETIC_6LBR_CONF
. $1/6lbr-functions

config_default

MODE_6LBR=$2
DEV=$3
OS=`uname`

if [ $MODE_6LBR != "tap" ]; then
	exit
fi

if [ "$(id -u)" != "0" ]; then
	echo "Running as non root, skipping interface deconfiguration"
	exit
fi

case $OS in
	Linux)
		ip link set $DEV down
		;;
	Darwin)
		;;
	*)
		echo Unknown OS
esac
