<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <project EXPORT="discard">[APPS_DIR]/mrm</project>
  <project EXPORT="discard">[APPS_DIR]/mspsim</project>
  <project EXPORT="discard">[APPS_DIR]/avrora</project>
  <project EXPORT="discard">[APPS_DIR]/serial_socket</project>
  <project EXPORT="discard">[APPS_DIR]/collect-view</project>
  <project EXPORT="discard">[APPS_DIR]/powertracker</project>
  <simulation>
    <title>6lbr template</title>
    <speedlimit>1.0</speedlimit>
    <randomseed>generated</randomseed>
    <motedelay_us>1000000</motedelay_us>
    <radiomedium>
      se.sics.cooja.radiomediums.UDGM
      <transmitting_range>45.0</transmitting_range>
      <interference_range>45.0</interference_range>
      <success_ratio_tx>1.0</success_ratio_tx>
      <success_ratio_rx>1.0</success_ratio_rx>
    </radiomedium>
    <events>
      <logoutput>40000</logoutput>
    </events>
    <motetype>
      se.sics.cooja.mspmote.SkyMoteType
      <identifier>6lbr</identifier>
      <description>6LBR manual routing</description>
      <source EXPORT="discard">[CONTIKI_DIR]/examples/6lowpan-nd/6lbr/ex-6lowpannd-6lbr.c</source>
      <commands EXPORT="discard">make ex-6lowpannd-6lbr.sky TARGET=sky WITH_STATISTICS=1</commands>
      <firmware EXPORT="copy">[CONTIKI_DIR]/examples/6lowpan-nd/6lbr/ex-6lowpannd-6lbr.sky</firmware>
      <moteinterface>se.sics.cooja.interfaces.Position</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.IPAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.MoteAttributes</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspClock</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspMoteID</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyButton</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyFlash</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyCoffeeFilesystem</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyByteRadio</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspSerial</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyLED</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspDebugOutput</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyTemperature</moteinterface>
    </motetype>
    <motetype>
      se.sics.cooja.mspmote.SkyMoteType
      <identifier>6lr</identifier>
      <description>6LR manual routing</description>
      <source EXPORT="discard">[CONTIKI_DIR]/examples/6lowpan-nd/6lr/ex-6lowpannd-6lr.c</source>
      <commands EXPORT="discard">make ex-6lowpannd-6lr.sky TARGET=sky WITH_STATISTICS=1</commands>
      <firmware EXPORT="copy">[CONTIKI_DIR]/examples/6lowpan-nd/6lr/ex-6lowpannd-6lr.sky</firmware>
      <moteinterface>se.sics.cooja.interfaces.Position</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.IPAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.MoteAttributes</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspClock</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspMoteID</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyButton</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyFlash</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyCoffeeFilesystem</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyByteRadio</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspSerial</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyLED</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspDebugOutput</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyTemperature</moteinterface>
    </motetype>
    <motetype>
      se.sics.cooja.mspmote.SkyMoteType
      <identifier>6lh</identifier>
      <description>6LH manual routing</description>
      <source EXPORT="discard">[CONTIKI_DIR]/examples/6lowpan-nd/6lh/ex-6lowpannd-6lh.c</source>
      <commands EXPORT="discard">make ex-6lowpannd-6lh.sky TARGET=sky WITH_STATISTICS=1</commands>
      <firmware EXPORT="copy">[CONTIKI_DIR]/examples/6lowpan-nd/6lh/ex-6lowpannd-6lh.sky</firmware>
      <moteinterface>se.sics.cooja.interfaces.Position</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.RimeAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.IPAddress</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.Mote2MoteRelations</moteinterface>
      <moteinterface>se.sics.cooja.interfaces.MoteAttributes</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspClock</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspMoteID</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyButton</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyFlash</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyCoffeeFilesystem</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyByteRadio</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspSerial</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyLED</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.MspDebugOutput</moteinterface>
      <moteinterface>se.sics.cooja.mspmote.interfaces.SkyTemperature</moteinterface>
    </motetype>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>1</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>0.0000000000000</x>
	<y>0.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lbr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>2</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>0.0000000000000</x>
	<y>35.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>3</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>0.0000000000000</x>
	<y>70.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>4</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>0.0000000000000</x>
	<y>105.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>5</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>35.0000000000000</x>
	<y>0.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>6</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>35.0000000000000</x>
	<y>35.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>7</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>35.0000000000000</x>
	<y>70.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>8</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>35.0000000000000</x>
	<y>105.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>9</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>70.0000000000000</x>
	<y>0.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>10</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>70.0000000000000</x>
	<y>35.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>11</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>70.0000000000000</x>
	<y>70.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>12</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>70.0000000000000</x>
	<y>105.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>13</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>105.0000000000000</x>
	<y>0.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>14</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>105.0000000000000</x>
	<y>35.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>15</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>105.0000000000000</x>
	<y>70.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lr</motetype_identifier>
    </mote>
    <mote>
      <breakpoints />
      <interface_config>
	se.sics.cooja.mspmote.interfaces.MspMoteID
	<id>16</id>
      </interface_config>
      <interface_config>
	se.sics.cooja.interfaces.Position
	<x>105.0000000000000</x>
	<y>105.0000000000000</y>
	<z>0.0000000000000</z>
      </interface_config>
      <motetype_identifier>6lh</motetype_identifier>
    </mote>
  </simulation>
  <plugin>
    se.sics.cooja.plugins.SimControl
    <width>280</width>
    <z>1</z>
    <height>160</height>
    <location_x>465</location_x>
    <location_y>0</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.Visualizer
    <plugin_config>
      <skin>se.sics.cooja.plugins.skins.IDVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.GridVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.TrafficVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.UDGMVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.MoteTypeVisualizerSkin</skin>
      <viewport>1.3090909090909089 0.0 0.0 1.3090909090909089 146.45454545454544 173.0</viewport>
    </plugin_config>
    <width>462</width>
    <z>6</z>
    <height>400</height>
    <location_x>1</location_x>
    <location_y>1</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.LogListener
    <plugin_config>
      <filter />
    </plugin_config>
    <width>1213</width>
    <z>7</z>
    <height>821</height>
    <location_x>466</location_x>
    <location_y>161</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.Notes
    <plugin_config>
      <notes>6LBR Test Support

This is an automatically generated COOJA simulation file

more information: https://github.com/cetic/6lbr/wiki/6LBR-Test-Environment</notes>
      <decorations>true</decorations>
    </plugin_config>
    <width>932</width>
    <z>2</z>
    <height>162</height>
    <location_x>745</location_x>
    <location_y>-1</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.ScriptRunner
    <plugin_config>
      <scriptfile>
        [CONFIG_DIR]/../grid_script.js
      </scriptfile>
      <active>true</active>
    </plugin_config>
    <width>462</width>
    <z>3</z>
    <height>335</height>
    <location_x>3</location_x>
    <location_y>646</location_y>
  </plugin>
  <plugin>
    be.cetic.cooja.plugins.RadioLoggerHeadless
    <width>216</width>
    <z>0</z>
    <height>103</height>
    <location_x>1501</location_x>
    <location_y>594</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>0</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>1</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>2</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>3</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>4</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>5</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>6</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>7</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>8</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>9</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>10</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>11</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>12</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>13</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>14</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
  <plugin>
    SerialSocketServer
    <mote_arg>15</mote_arg>
    <width>459</width>
    <z>4</z>
    <height>119</height>
    <location_x>5</location_x>
    <location_y>525</location_y>
  </plugin>
</simconf>

