PROJECT=6lbr-demo

CONTIKI=../../../../../..
PROJECTDIRS+=../../../../../6lbr-demo/

WITH_SHELL=1
WITH_DELAY_IP=0
WITH_UDPCLIENT=1
WITH_WEBSERVER=0
UDP_PERIOD=5

include ../../../../../6lbr-demo/Makefile
