CFLAGS += -DCETIC_6LBR_NODE_CONFIG=1
node-config_src = node-config.c

ifeq ($(WITH_IP64),1)
CFLAGS +=-DIP64_SPECIAL_PORTS_CONF_ENABLE=1
node-config_src += node-config-ip64-ports.c
endif

ifeq ($(TARGET),native)
node-config_src += node-config-file.c
else
node-config_src += node-config-memb.c
endif
