#ifndef DEVICE_RESOURCE_H_
#define DEVICE_RESOURCE_H_

#include "contiki.h"

#ifdef REST_CONF_RES_DEVICE_MANUFACTURER
#define REST_RES_DEVICE_MANUFACTURER REST_CONF_RES_DEVICE_MANUFACTURER
#else
#define REST_RES_DEVICE_MANUFACTURER 1
#endif

#ifdef REST_CONF_RES_DEVICE_MODEL
#define REST_RES_DEVICE_MODEL REST_CONF_RES_DEVICE_MODEL
#else
#define REST_RES_DEVICE_MODEL 1
#endif

#ifdef REST_CONF_RES_DEVICE_MODEL_HW
#define REST_RES_DEVICE_MODEL_HW REST_CONF_RES_DEVICE_MODEL_HW
#else
#define REST_RES_DEVICE_MODEL_HW 1
#endif

#ifdef REST_CONF_RES_DEVICE_MODEL_SW
#define REST_RES_DEVICE_MODEL_SW REST_CONF_RES_DEVICE_MODEL_SW
#else
#define REST_RES_DEVICE_MODEL_SW 1
#endif

#ifdef REST_CONF_RES_DEVICE_SERIAL
#define REST_RES_DEVICE_SERIAL REST_CONF_RES_DEVICE_SERIAL
#else
#define REST_RES_DEVICE_SERIAL 1
#endif

#ifdef REST_CONF_RES_DEVICE_NAME
#define REST_RES_DEVICE_NAME REST_CONF_RES_DEVICE_NAME
#else
#define REST_RES_DEVICE_NAME 1
#endif

#ifdef REST_CONF_RES_DEVICE_TIME
#define REST_RES_DEVICE_TIME REST_CONF_RES_DEVICE_TIME
#else
#define REST_RES_DEVICE_TIME 1
#endif

#ifdef REST_CONF_RES_DEVICE_UPTIME
#define REST_RES_DEVICE_UPTIME REST_CONF_RES_DEVICE_UPTIME
#else
#define REST_RES_DEVICE_UPTIME 1
#endif

#if REST_RES_DEVICE_MANUFACTURER
#define REST_RES_DEVICE_MANUFACTURER_INIT() INIT_RESOURCE(device_manufacturer, DEVICE_MANUFACTURER_RES);
#else
#define REST_RES_DEVICE_MANUFACTURER_INIT()
#endif

#if REST_RES_DEVICE_MODEL
#define REST_RES_DEVICE_MODEL_INIT() INIT_RESOURCE(device_model, DEVICE_MODEL_RES);
#else
#define REST_RES_DEVICE_MODEL_INIT()
#endif

#if REST_RES_DEVICE_MODEL_HW
#define REST_RES_DEVICE_MODEL_HW_INIT() INIT_RESOURCE(device_model_hw, DEVICE_MODEL_HW_RES);
#else
#define REST_RES_DEVICE_MODEL_HW_INIT()
#endif

#if REST_RES_DEVICE_MODEL_SW
#define REST_RES_DEVICE_MODEL_SW_INIT() INIT_RESOURCE(device_model_sw, DEVICE_MODEL_SW_RES);
#else
#define REST_RES_DEVICE_MODEL_SW_INIT()
#endif

#if REST_RES_DEVICE_SERIAL
#define REST_RES_DEVICE_SERIAL_INIT() INIT_RESOURCE(device_serial, DEVICE_SERIAL_RES);
#else
#define REST_RES_DEVICE_SERIAL_INIT()
#endif

#if REST_RES_DEVICE_NAME
#define REST_RES_DEVICE_NAME_INIT() INIT_RESOURCE(device_name, DEVICE_NAME_RES);
#else
#define REST_RES_DEVICE_NAME_INIT()
#endif

#if REST_RES_DEVICE_TIME
#define REST_RES_DEVICE_TIME_INIT() INIT_RESOURCE(device_time, DEVICE_TIME_RES);
#else
#define REST_RES_DEVICE_TIME_INIT()
#endif

#if REST_RES_DEVICE_UPTIME
#define REST_RES_DEVICE_UPTIME_INIT() INIT_RESOURCE(device_uptime, DEVICE_UPTIME_RES);
#else
#define REST_RES_DEVICE_UPTIME_INIT()
#endif

#define REST_RES_DEVICE_DEFINE()

#define REST_RES_DEVICE_INIT() \
  REST_RES_DEVICE_MANUFACTURER_INIT(); \
  REST_RES_DEVICE_MODEL_INIT(); \
  REST_RES_DEVICE_MODEL_HW_INIT(); \
  REST_RES_DEVICE_MODEL_SW_INIT(); \
  REST_RES_DEVICE_SERIAL_INIT(); \
  REST_RES_DEVICE_NAME_INIT(); \
  REST_RES_DEVICE_TIME_INIT(); \
  REST_RES_DEVICE_UPTIME_INIT();

#endif /* DEVICE_RESOURCE_H_ */
