#include "coap-common.h"
#include "humidity-sensor-resource.h"

#if REST_RES_HUMIDITY
#if REST_RES_HUMIDITY_PERIODIC
#define REST_RES_HUMIDITY_RESOURCE REST_PERIODIC_RESOURCE
#else
#define REST_RES_HUMIDITY_RESOURCE REST_RESOURCE
#endif
#else
#define REST_RES_HUMIDITY_RESOURCE(...)
#endif

#if REST_RES_HUMIDITY_RAW
#define REST_REST_HUMIDITY_VALUE REST_FORMAT_ONE_INT("v", sht11_sensor.value(SHT11_SENSOR_HUMIDITY))
#else
#define REST_REST_HUMIDITY_VALUE REST_FORMAT_ONE_DECIMAL("v", sht11_sensor.value(SHT11_SENSOR_HUMIDITY)/819, (10*sht11_sensor.value(SHT11_SENSOR_HUMIDITY)/819) % 10)
#endif

REST_RES_HUMIDITY_RESOURCE(humidity,
    REST_RES_HUMIDITY_PERIOD,
    HUMIDITY_SENSOR_RES,
    IF_SENSOR,
    RELATIVE_HUMIDITY_RT,
    REST_REST_HUMIDITY_VALUE)
