#include "coap-common.h"
#include "light-sensor-resource.h"

#if REST_RES_LIGHT
#if REST_RES_LIGHT_PERIODIC
#define REST_RES_LIGHT_RESOURCE REST_PERIODIC_RESOURCE
#else
#define REST_RES_LIGHT_RESOURCE REST_RESOURCE
#endif
#else
#define REST_RES_LIGHT_RESOURCE(...)
#endif

#if REST_RES_LIGHT_RAW
#define LIGHT_PHOTOSYNTHETIC_VALUE REST_FORMAT_ONE_INT(LIGHT_PHOTOSYNTHETIC_SENSOR_RES, light_sensor.value(LIGHT_SENSOR_PHOTOSYNTHETIC))
#define LIGHT_SOLAR_VALUE REST_FORMAT_ONE_INT(LIGHT_SOLAR_SENSOR_RES, light_sensor.value(LIGHT_SENSOR_TOTAL_SOLAR))
#else
#define LIGHT_PHOTOSYNTHETIC_VALUE REST_FORMAT_ONE_INT(LIGHT_PHOTOSYNTHETIC_SENSOR_RES, (light_sensor.value(LIGHT_SENSOR_PHOTOSYNTHETIC) * 10) / 7)
#define LIGHT_SOLAR_VALUE REST_FORMAT_ONE_INT(LIGHT_SOLAR_SENSOR_RES, (light_sensor.value(LIGHT_SENSOR_TOTAL_SOLAR) * 46) / 10)
#endif

REST_RES_LIGHT_RESOURCE(light_photo,
    REST_RES_LIGHT_PERIOD,
    SENSOR_PATH LIGHT_PHOTOSYNTHETIC_SENSOR_RES,
    IF_SENSOR,
    LIGHT_RAW_RT,
    LIGHT_PHOTOSYNTHETIC_VALUE)

REST_RES_LIGHT_RESOURCE(light_solar,
    REST_RES_LIGHT_PERIOD,
    SENSOR_PATH LIGHT_SOLAR_SENSOR_RES,
    IF_SENSOR,
    LIGHT_RAW_RT,
    LIGHT_SOLAR_VALUE)
