/*
 * Copyright (c) 2015, CETIC.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the Institute nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/**
 * \file
 *         Simple CoAP Library
 * \author
 *         6LBR Team <6lbr@cetic.be>
 */
#ifndef LWM2M_PROFILE_H
#define LWM2M_PROFILE_H

#define LWM2M_OBJECT_ID_SECURITY "0"
#define LWM2M_OBJECT_ID_SERVER "1"
#define LWM2M_OBJECT_ID_ACCESS_CONTROL "2"
#define LWM2M_OBJECT_ID_DEVICE "3"
#define LWM2M_OBJECT_ID_CONNECTIVITY_MONITORING "4"
#define LWM2M_OBJECT_ID_FIRMWARE "5"
#define LWM2M_OBJECT_ID_LOCATION "6"
#define LWM2M_OBJECT_ID_CONNECTIVITY_STATISTICS "7"

#define LWM2M_INSTANCE_DEVICE LWM2M_OBJECT_ID_DEVICE "/0"

#define LWM2M_ITEM_ID_DEVICE_MANUFACTURER LWM2M_INSTANCE_DEVICE "/0"
#define LWM2M_ITEM_ID_DEVICE_MODEL_NUMBER LWM2M_INSTANCE_DEVICE "/1"
#define LWM2M_ITEM_ID_DEVICE_SERIAL_NUMBER LWM2M_INSTANCE_DEVICE "/2"
#define LWM2M_ITEM_ID_DEVICE_FIRMWARE LWM2M_INSTANCE_DEVICE "/3"
#define LWM2M_ITEM_ID_DEVICE_REBOOT LWM2M_INSTANCE_DEVICE "/4"
#define LWM2M_ITEM_ID_DEVICE_FACTORY_RESET LWM2M_INSTANCE_DEVICE "/5"
#define LWM2M_ITEM_ID_DEVICE_POWER LWM2M_INSTANCE_DEVICE "/6"
#define LWM2M_ITEM_ID_DEVICE_POWER_VOLTAGE LWM2M_INSTANCE_DEVICE "/7"
#define LWM2M_ITEM_ID_DEVICE_POWER_CURRENT LWM2M_INSTANCE_DEVICE "/8"
#define LWM2M_ITEM_ID_DEVICE_BATTERY_LEVEL LWM2M_INSTANCE_DEVICE "/9"
#define LWM2M_ITEM_ID_DEVICE_MEMORY_FREE LWM2M_INSTANCE_DEVICE "/10"
#define LWM2M_ITEM_ID_DEVICE_ERROR_CODE LWM2M_INSTANCE_DEVICE "/11"
#define LWM2M_ITEM_ID_DEVICE_RESET_ERROR_CODE LWM2M_INSTANCE_DEVICE "/12"
#define LWM2M_ITEM_ID_DEVICE_CURRENT_TIME LWM2M_INSTANCE_DEVICE "/13"
#define LWM2M_ITEM_ID_DEVICE_UTC_OFFSET LWM2M_INSTANCE_DEVICE "/14"
#define LWM2M_ITEM_ID_DEVICE_TIMEZONE LWM2M_INSTANCE_DEVICE "/15"
#define LWM2M_ITEM_ID_DEVICE_BINDING LWM2M_INSTANCE_DEVICE "/16"

#define LWM2M_OBJECT_DEVICE_RT ""
#define LWM2M_OBJECT_DEVICE_MANUFACTURER_RT ""
#define LWM2M_OBJECT_DEVICE_MODEL_NUMBER_RT ""
#define LWM2M_OBJECT_DEVICE_SERIAL_NUMBER_RT ""
#define LWM2M_OBJECT_DEVICE_FIRMWARE_RT ""
#define LWM2M_OBJECT_DEVICE_REBOOT_RT ""
#define LWM2M_OBJECT_DEVICE_TIME_RT ""

void
lwm2m_init(void);

#endif /* LWM2M_PROFILE_H */
