#include "coap-common.h"
#include "radio-sensor-resource.h"

#if REST_RES_RADIO_LQI
#if REST_RES_RADIO_LQI_PERIODIC
#define REST_RES_RADIO_LQI_RESOURCE REST_PERIODIC_RESOURCE
#else
#define REST_RES_RADIO_LQI_RESOURCE REST_RESOURCE
#endif
#else
#define REST_RES_RADIO_LQI_RESOURCE(...)
#endif

#if REST_RES_RADIO_RSSI
#if REST_RES_RADIO_RSSI_PERIODIC
#define REST_RES_RADIO_RSSI_RESOURCE REST_PERIODIC_RESOURCE
#else
#define REST_RES_RADIO_RSSI_RESOURCE REST_RESOURCE
#endif
#else
#define REST_RES_RADIO_RSSI_RESOURCE(...)
#endif

#if REST_RES_RADIO_LQI_RAW
#define RADIO_LQI_VALUE REST_FORMAT_ONE_INT("lqi", radio_sensor.value(RADIO_SENSOR_LAST_PACKET))
#else
#define RADIO_LQI_VALUE REST_FORMAT_ONE_INT("lqi", (radio_sensor.value(RADIO_SENSOR_LAST_PACKET) - 50) * 255 / 110)
#endif

#if REST_RES_RADIO_RSSI_RAW
#define RADIO_RSSI_VALUE REST_FORMAT_ONE_INT("rssi", radio_sensor.value(RADIO_SENSOR_LAST_VALUE))
#else
#define RADIO_RSSI_VALUE REST_FORMAT_ONE_INT("rssi", (radio_sensor.value(RADIO_SENSOR_LAST_VALUE) - 45))
#endif

REST_RES_RADIO_RSSI_RESOURCE(radio_rssi,
    REST_RES_RADIO_RSSI_PERIOD,
    RADIO_RSSI_SENSOR_RES,
    IF_SENSOR,
    DBM_RT,
    RADIO_RSSI_VALUE)

REST_RES_RADIO_LQI_RESOURCE(radio_lqi,
    REST_RES_RADIO_LQI_PERIOD,
    RADIO_LQI_SENSOR_RES,
    IF_SENSOR,
    PERCENT_RT,
    RADIO_LQI_VALUE)
