CFLAGS += -DWEBSERVER=1
6lbr-webserver_src = httpd.c httpd-cgi.c httpd-urlconv.c webserver.c webserver-utils.c \
    webserver-main.c webserver-network.c \
    webserver-config.c webserver-statistics.c webserver-admin.c webserver-log.c

ifeq ($(CONTIKI_WITH_RPL),1)
6lbr-webserver_src+= webserver-rpl.c
endif

ifeq ($(TARGET),native)
6lbr-webserver_src += webserver-file.c
endif

ifneq ($(WITH_NODE_INFO),0)
6lbr-webserver_src += webserver-sensors.c webserver-sensor.c
endif
