er-coap-13_src = er-coap-13.c er-coap-13-engine.c er-coap-13-transactions.c er-coap-13-observing.c er-coap-13-separate.c
ifeq ($(WITH_DTLS_COAP),1)
CFLAGS += -DWITH_DTLS_COAP=1
er-coap-13_src += er-coap-13-dtls.c
else
CFLAGS += -DWITH_DTLS_COAP=0
er-coap-13_src += er-coap-13-udp.c
endif
